name = "DeepSeek V3.2"
description = "Optimized for reasoning chat completions"
family = "deepseek"
release_date = "2026-07-07"
last_updated = "2026-07-07"
attachment = false
reasoning = true
reasoning_options = []
tool_call = true
temperature = true
open_weights = true

[cost]
input = 0.76
output = 2.29

[limit]
context = 163_840
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
